### ISSUE TITLE
Kodi and tvdb zip file issue workaround

### ISSUE THREAD

**Issue by slohj** [ScudLee/scudlee-xbmc-addons#5]
Due to the recent changes at the tvdb, the downloaded can not not be extracted by anidb[mod] extractor due to a zip file format compatibility issue.  I have a little bash function that is a work around.  first scrape as normal, then run this function, then refresh all the new episodes from the internet,  anidb[mod] will use the proper cached tvdb-xxx.xml file.

tvdb_fix ()
{
    xml_dir="${HOME}/.kodi/temp/scrapers/metadata.tvshows.anidb.net.mod"
    for file in ${xml_dir}/tvdb-*.xml
    do
        if [[ $(file "${file}") =~ Zip ]]
        then
            mv -v "${file}" "${file}.zip"
            unzip -p "${file}.zip" en.xml > "${file}"
            rm "${file}.zip"
        fi
    done
}

**Comment by arucard21** [comment]
Thanks for this, really helped. I also noticed that the scraper is no longer retrieving any artwork. I only get the poster from AniDB but no fanart or banner from thetvdb. Any ideas on that, or should I just create a separate issue for it?

**Comment by slohj** [comment]
It's part of the same problem.  The links to artwork will be populated after a rescan, once the tvdb data has been extracted and renamed.  artworkbeef also needs the rescan to work properly.  I wish I had the time and knowledge to fix this properly.  I'm also assuming that the anidb movie scraper problem is similar in nature.
I think the more issues opened the better, but I think these plugins should be considered abandoned.  Scudlee hasn't been seen over on  anime-lists repo for over a year, those of us with commit privs there are just muddling along on that one.

**Comment by arucard21** [comment]
For me, the fanart wasn't populated after the rescan. But this might be a different problem, with tvdb instead. I think they no longer allow HTTP access, only HTTPS. 

And isn't it worth considering a fork, if this repo has been abandoned? I couldn't really find another AniDB scraper so this is the only option I have (since I don't want to use the tvdb scraper as that requires different names and folder structure).

**Comment by slohj** [comment]
the tvdb did change their api, that is the cause of all of this.  Artworkbeef was updated to handle this.  You need to make sure that you use the tvdb id on the first page of the anidb scraper settings.  It all works for me except for the all too common times that the tvdb won't talk to artworkbeef, but that's another problem that's beyond control.

**Comment by arucard21** [comment]
Ah, Artworkbeef is an addon. I'll install it then. It used to work fine without it, with this scraper retrieving the fanart from tvdb so I didn't have this installed. Thanks for the help. I haven't quite gotten Artworkbeef to work correctly yet but that's an unrelated problem.

**Comment by slohj** [comment]
Fixed in latest commit.
